update datasets.classification set histclass1='.' where histclass1 is null;
update datasets.classification set histclass1='.' where histclass1='0';
update datasets.classification set histclass1='.' where histclass1='';
update datasets.classification set histclass2='.' where histclass2 is null;
update datasets.classification set histclass2='.' where histclass2='0';
update datasets.classification set histclass2='.' where histclass2='';
update datasets.classification set histclass3='.' where histclass3 is null;
update datasets.classification set histclass3='.' where histclass3='0';
update datasets.classification set histclass3='.' where histclass3='';
update datasets.classification set histclass4='.' where histclass4 is null;
update datasets.classification set histclass4='.' where histclass4='0';
update datasets.classification set histclass4='.' where histclass4='';
update datasets.classification set histclass5='.' where histclass5 is null;
update datasets.classification set histclass5='.' where histclass5='0';
update datasets.classification set histclass5='.' where histclass5='';
update datasets.classification set histclass6='.' where histclass6 is null;
update datasets.classification set histclass6='.' where histclass6='0';
update datasets.classification set histclass6='.' where histclass6='';
update datasets.classification set histclass7='.' where histclass7 is null;
update datasets.classification set histclass7='.' where histclass7='0';
update datasets.classification set histclass7='.' where histclass7='';
update datasets.classification set histclass8='.' where histclass8 is null;
update datasets.classification set histclass8='.' where histclass8='0';
update datasets.classification set histclass8='.' where histclass8='';
update datasets.classification set histclass9='.' where histclass9 is null;
update datasets.classification set histclass9='.' where histclass9='0';
update datasets.classification set histclass9='.' where histclass9='';
update datasets.classification set histclass10='.' where histclass10 is null;
update datasets.classification set histclass10='.' where histclass10='0';
update datasets.classification set histclass10='.' where histclass10='';
update datasets.classification set class1='.' where class1 is null;
update datasets.classification set class1='.' where class1='0';
update datasets.classification set class2='.' where class2 is null;
update datasets.classification set class2='.' where class2='0';
update datasets.classification set class3='.' where class3 is null;
update datasets.classification set class3='.' where class3='0';
update datasets.classification set class4='.' where class4 is null;
update datasets.classification set class4='.' where class4='0';
update datasets.classification set class5='.' where class5 is null;
update datasets.classification set class5='.' where class5='0';
update datasets.classification set class6='.' where class6 is null;
update datasets.classification set class6='.' where class6='0';
update datasets.classification set class7='.' where class7 is null;
update datasets.classification set class7='.' where class7='0';
update datasets.classification set class8='.' where class8 is null;
update datasets.classification set class8='.' where class8='0';
update datasets.classification set class9='.' where class9 is null;
update datasets.classification set class9='.' where class9='0';
update datasets.classification set class10='.' where class10 is null;
update datasets.classification set class10='.' where class10='0';
